import type { ReactNode } from "react";
import { AiExecutiveSummaryCard } from "@/components/report/AiExecutiveSummaryCard";
import { DetailedSummarySection } from "@/components/report/DetailedSummarySection";
import { FeatureQaSummaryTable } from "@/components/report/FeatureQaSummaryTable";
import { IssueReviewCardsSection } from "@/components/report/IssueReviewCardsSection";
import { IssuePatternAnalysisCard } from "@/components/report/IssuePatternAnalysisCard";
import { RcProgressCard } from "@/components/report/RcProgressCard";
import { ReleaseRiskSummaryCard } from "@/components/report/ReleaseRiskSummaryCard";
import { ReportDashboardHeader } from "@/components/report/ReportDashboardHeader";
import { Plus } from "lucide-react";
import type {
  AiExecutiveSummaryResult,
  AnalysisSummaryState,
} from "@/types/report";

type OverallReportDashboardProps = {
  analysisSummary: NonNullable<AnalysisSummaryState>;
  reportScopeText: string;
  reportTitleText: string;
  reportPeriodText: string;
  reportVersionText: string;
  reportRcText: string;
  generatedAtText: string;
  aiAnalysisText: string;
  aiExecutiveSummary: AiExecutiveSummaryResult | null;
  isAiAnalyzing: boolean;
  onStartNewReport: () => void;
  children: ReactNode;
};

export function OverallReportDashboard({
  analysisSummary,
  reportScopeText,
  reportTitleText,
  reportPeriodText,
  reportVersionText,
  reportRcText,
  generatedAtText,
  aiAnalysisText,
  aiExecutiveSummary,
  isAiAnalyzing,
  onStartNewReport,
  children,
}: OverallReportDashboardProps) {
  const trimmedReportTitle = reportTitleText.trim();
  const qaResultTitle =
    trimmedReportTitle.length > 0
      ? /QA\s*결과/i.test(trimmedReportTitle)
        ? trimmedReportTitle
        : `${trimmedReportTitle} QA 결과`
      : "전체 QA 결과";

  return (
    <div className="space-y-5">
      <ReportDashboardHeader
        analysisSummary={analysisSummary}
        reportScopeText={reportScopeText}
        reportPeriodText={reportPeriodText}
        reportVersionText={reportVersionText}
        reportRcText={reportRcText}
        generatedAtText={generatedAtText}
        aiExecutiveSummary={aiExecutiveSummary}
        isAiAnalyzing={isAiAnalyzing}
        eyebrow={null}
        title="전체 QA 결과 리포트"
        primaryText={qaResultTitle}
      />
      <AiExecutiveSummaryCard
        analysisSummary={analysisSummary}
        analysisText={aiAnalysisText}
        aiExecutiveSummary={aiExecutiveSummary}
        isLoading={isAiAnalyzing}
      />
      <div className="grid grid-cols-3 items-stretch gap-5">
        <div className="min-w-0">
          <ReleaseRiskSummaryCard analysisSummary={analysisSummary} />
        </div>
        <div className="min-w-0">
          <RcProgressCard rcProgress={analysisSummary.rcProgress} />
        </div>
        <div className="min-w-0">
          <FeatureQaSummaryTable analysisSummary={analysisSummary} />
        </div>
      </div>
      <IssuePatternAnalysisCard analysisSummary={analysisSummary} />
      <IssueReviewCardsSection analysisSummary={analysisSummary} />
      <DetailedSummarySection>{children}</DetailedSummarySection>
      <div className="flex justify-end" data-export-ignore="true">
        <button
          type="button"
          onClick={onStartNewReport}
          className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 shadow-sm transition hover:border-indigo-200 hover:bg-slate-50 hover:text-indigo-700"
        >
          <Plus className="size-4 text-indigo-500" aria-hidden="true" />
          <span>새 리포트 작성하기</span>
        </button>
      </div>
      <footer className="border-t border-slate-200 pt-4 text-xs text-slate-400">
        <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
          <span>Generated by AI QA Report Assistant</span>
          <span>Data based on QA Result / Jira / RC Summary</span>
        </div>
      </footer>
    </div>
  );
}
