import type { ReactNode } from "react";
import { AiExecutiveSummaryCard } from "@/components/report/AiExecutiveSummaryCard";
import { DetailedSummarySection } from "@/components/report/DetailedSummarySection";
import { FeatureQaSummaryTable } from "@/components/report/FeatureQaSummaryTable";
import { IssuePatternAnalysisCard } from "@/components/report/IssuePatternAnalysisCard";
import { QaFollowUpDashboardCard } from "@/components/report/QaFollowUpDashboardCard";
import { RcProgressCard } from "@/components/report/RcProgressCard";
import { ReleaseRiskSummaryCard } from "@/components/report/ReleaseRiskSummaryCard";
import { RemainingIssuesDashboardCard } from "@/components/report/RemainingIssuesDashboardCard";
import { ReportDashboardHeader } from "@/components/report/ReportDashboardHeader";
import type {
  AiExecutiveSummaryResult,
  AnalysisSummaryState,
  MessageState,
} from "@/types/report";

type OverallReportDashboardProps = {
  analysisSummary: NonNullable<AnalysisSummaryState>;
  reportScopeText: string;
  reportPeriodText: string;
  reportVersionText: string;
  reportRcText: string;
  generatedAtText: string;
  aiAnalysisText: string;
  aiExecutiveSummary: AiExecutiveSummaryResult | null;
  isAiAnalyzing: boolean;
  onAnalyze: () => void;
  onCreateResultSheet: () => void;
  isCreatingResultSheet: boolean;
  resultSheetMessage: MessageState;
  resultSheetUrl: string;
  children: ReactNode;
};

export function OverallReportDashboard({
  analysisSummary,
  reportScopeText,
  reportPeriodText,
  reportVersionText,
  reportRcText,
  generatedAtText,
  aiAnalysisText,
  aiExecutiveSummary,
  isAiAnalyzing,
  onAnalyze,
  onCreateResultSheet,
  isCreatingResultSheet,
  resultSheetMessage,
  resultSheetUrl,
  children,
}: OverallReportDashboardProps) {
  return (
    <div className="space-y-5">
      <ReportDashboardHeader
        analysisSummary={analysisSummary}
        reportScopeText={reportScopeText}
        reportPeriodText={reportPeriodText}
        reportVersionText={reportVersionText}
        reportRcText={reportRcText}
        generatedAtText={generatedAtText}
        onCreateResultSheet={onCreateResultSheet}
        isCreatingResultSheet={isCreatingResultSheet}
        resultSheetMessage={resultSheetMessage}
        resultSheetUrl={resultSheetUrl}
      />
      <AiExecutiveSummaryCard
        analysisSummary={analysisSummary}
        analysisText={aiAnalysisText}
        aiExecutiveSummary={aiExecutiveSummary}
        isLoading={isAiAnalyzing}
        onAnalyze={onAnalyze}
      />
      <div className="grid items-stretch gap-5 lg:grid-cols-3">
        <div className="min-w-0">
          <ReleaseRiskSummaryCard analysisSummary={analysisSummary} />
        </div>
        <div className="min-w-0">
          <RcProgressCard rcProgress={analysisSummary.rcProgress} />
        </div>
        <div className="min-w-0">
          <FeatureQaSummaryTable analysisSummary={analysisSummary} />
        </div>
      </div>
      <IssuePatternAnalysisCard analysisSummary={analysisSummary} />
      <div className="grid items-stretch gap-5 md:grid-cols-2">
        <div className="min-w-0">
          <RemainingIssuesDashboardCard analysisSummary={analysisSummary} />
        </div>
        <div className="min-w-0">
          <QaFollowUpDashboardCard analysisSummary={analysisSummary} />
        </div>
      </div>
      <DetailedSummarySection>{children}</DetailedSummarySection>
      <footer className="border-t border-slate-200 pt-4 text-xs text-slate-400">
        <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
          <span>Generated by AI QA Report Assistant</span>
          <span>Data based on QA Result / Jira / RC Summary</span>
        </div>
      </footer>
    </div>
  );
}
